### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by shinozaki-0722** [shinozaki-0722/chat-space#9]
# IPアドレス
54.150.234.211

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○グループ編集後、「更新」を押すと、トップページに飛んでしまう為、当該グループのチャットページ（サイドバープラスメッセージ履歴表示ページ）に飛べるようにしましょう。**

[参考]
https://master.tech-camp.in/curriculums/4049

**[現在はグループ編集→更新する→トップページ]**
<img width="1025" alt="スクリーンショット 2020-07-14 11 17 04" src="https://user-images.githubusercontent.com/65144927/87373248-47f93e00-c5c4-11ea-8f60-1e1b2d2f5d1d.png">


**[理想：グループ編集→更新する→当該グループのチャットページ]**
<img width="1025" alt="スクリーンショット 2020-07-14 11 16 50" src="https://user-images.githubusercontent.com/65144927/87373304-68c19380-c5c4-11ea-9c79-8dd467b49096.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shinozaki-0722** [comment]
グループ編集後に更新をするとトップページに飛んでしまうとのことですが、私の環境で実施するとそのグループのチャットページに飛びます。
ローカル環境、リモート環境両方ともで試してみましたが大丈夫でした。
お手数ですがもう一度確認お願い致します。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、前回の指摘箇所も含め、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by shinozaki-0722** [comment]
動作確認ありがとうございました。
